- name: Configure web servers
  hosts: all
  become: true
  tasks:
  - name: Install the latest version of Apache web server
    apt: name=apache2 update_cache=yes state=latest #state=present
  - name: Start Apache service
    service: name=apache2 state=started

# - name: Configure database servers
#   hosts: db
#   become: true
#   tasks:
#   - name: Install MySQL server
#     apt: name=mysql-server state=present
#   - name: Start MySQL service
#     service: name=mysql state=started
  # - name: Create database
  #   mysql_db: name=mydb state=present
  # - name: Create database user
  #   mysql_user: name=myuser password=mypassword priv=mydb.*:ALL state=present